name: Java CI Deploy

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Give executable permission to Gradle wrapper file
      run: chmod +x gradlew
    - name: Publish artifact as package
      run: ./gradlew publish -Pusername=edduarte -Ptoken=${{ secrets.GITHUB_TOKEN }}
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: ""
        draft: true
        prerelease: false
