name: Java CI Deploy

on:
  # Trigger the workflow when a release is published
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Give executable permission to Gradle wrapper file
      run: chmod +x gradlew
    - name: Publish
      run: ./gradlew publish -Pusername=edduarte -Ptoken=${{ secrets.GITHUB_TOKEN }}
